services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-production
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bprd
      - JWT_SECRET=sua_frase_secreta_super_secreta
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: